version: 1.0.{build}

image: Visual Studio 2017

before_build:
- nuget restore src\RaboOmniKassaApi.Net.sln

build:
  project: src\RaboOmniKassaApi.Net.sln
  verbosity: minimal
  
test:
  assemblies:
    - src\RaboOmniKassaApi.Tests\bin\Debug\RaboOmniKassaApi.Tests.dll

after_test:
- .\src\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user "-filter:+[RaboOmniKassaApi*]*" -target:"vstest.console.exe" -targetargs:"/logger:Appveyor .\src\RaboOmniKassaApi.Tests\bin\Debug\RaboOmniKassaApi.Tests.dll" -output:".\coverage.xml"
- .\src\packages\Codecov.1.0.5\tools\codecov -f "coverage.xml"